apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
